api_platform:
  title: SIMPLON CANDIDATURE API AVEC SYMFONY
  description: Une API qui permet a simplon senegal de gerer les candidatures qu'ils reçoivent lors de leur lancement de formations
  version: 1.0.0
  formats:
    jsonld: ["application/ld+json"]
  docs_formats:
    jsonld: ["application/ld+json"]
    jsonopenapi: ["application/vnd.openapi+json"]
    html: ["text/html"]
  defaults:
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
    extra_properties:
      standard_put: true
      rfc_7807_compliant_errors: true
  event_listeners_backward_compatibility_layer: false
  keep_legacy_inflector: false
  eager_loading:
    max_joins: 100

  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
