version: '3'

services:
  app:
    build: .
    image: simplon_candidature
    container_name: Conteneur_Simplon_Candidature
    ports:
      - 9090:80

    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9000:80
    environment:
      PMA_ARBITRARY: 1

volumes:
  db-data:
