version: '3'

services:
  db:
    image: mysql:8.2
    container_name: mysql_api
    restart: always
    ports:
      - 8080:3306
    environment:
      MYSQL_DATABASE: Candidature
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - dev
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_api
    restart: always
    links:
      - db
    ports:
      - 9000:80
    environment:
      MYSQL_USERNAME: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - dev

  app:
    build:
      context: .
      dockerfile: docker/dockerfile
    image: api_simplon_symfony
    container_name: Conteneur_Simplon_Candidature
    ports:
      - 9090:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - dev

networks:
  dev:
volumes:
  db-data:
